services:
  db:
    restart: always
    build: ./sql
    #image: mysql:8.0.39
    container_name: mysql_container
    healthcheck:
      test: ["CMD", "mysqladmin", "ping","--protocol","tcp"]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      MYSQL_DATABASE: fechatbot
      MYSQL_USER: axl
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    logging:
      driver: "json-file"
      options:
        max-size: "5m"      # Tamaño máximo de cada archivo de log
        max-file: "3"        # Número máximo de archivos de log a retener
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql    
    networks:
      - fechatbot-network  

  python-service:
    restart: always
    build: 
      context: ./python-service
    container_name: python_container
    env_file: python-service/app/DownloadFile/.env
    logging:
      driver: "json-file"
      options:
        max-size: "5m"      # Tamaño máximo de cada archivo de log
        max-file: "3"        # Número máximo de archivos de log a retener
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fechatbot-network

  node-service:
    restart: always
    build: 
      context: ./node-service
    container_name: node_container
    logging:
      driver: "json-file"
      options:
        max-size: "5m"      # Tamaño máximo de cada archivo de log
        max-file: "3"        # Número máximo de archivos de log a retener
    depends_on:
      - python-service
    networks:
      - fechatbot-network

  nginx:
    restart: always
    build:
      context: ./nginx
    logging:
      driver: "json-file"
      options:
        max-size: "5m"      # Tamaño máximo de cada archivo de log
        max-file: "3"        # Número máximo de archivos de log a retener
    ports:
      - "80:80"
    networks:
      - fechatbot-network

networks:
  fechatbot-network:
    driver: bridge
  
#Names our volume
#volumes:
#  mysql_data: