FROM nginx
#nginx.conf it is found in /etc/nginx.
#There is no folder called servers in the Docker distribution of Nginx. 
#Instead there is a folder called conf.d which stores all custom configurations. 
COPY default.conf /etc/nginx/conf.d/default.conf